language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: KjwpWPpTJqaejSg3YOd7AIm8qex8G9ghcfumVQQlbe2r3h4THSsfLde1ARhmJ4O1pahwr8bSkrqC1zM91nBi2WhhCrHdqbMoGk2KRuAb/ihls7QXhx/J4o9A9wU7P+2lNMnT7pXPorqK5ALAtnsHJ/tXzz0pqATCpelx+BxQd3IaRcpOlWvPMWaR6urpVc63IijgDkgEbmYeEQ3bcejyyPqox3ekVZfRtqx2W6png/0a8Fk4qsc6ad0OCvNPrZYR9H0/Rc+qn8hvq18B8VWmF1ULKAOmFploIaMLqxDAW3hkiKVV2t65EDho9L73WzeDe+n4ZsQz40Ta8IMhNcfMjDFnLyJgVHTTx1LZHLPnGw9dEKvkumFBjl55FzK0TQRNVyeOwRHCi9SzSfUXN29CUN6lc7YKCnkvVD5SaUCjky7lLbkd1XjRDWMEEpDZaVaDRY6EoDioG7d+AiaYCVKj2YT3SkOj0kZ9S5Byw/GONk8WnqLxCkX/1SC6BVdnJepQBf7AcA3CCBUY3wRXH6KyWGdAEsBAUbx7k/iw22GSbUAVjRqL0YK4QNjnGE6alb0LE37cMVGqOaAlT2+GMsEli8e+/lSUtCOIPKvAPVtoC71sJ0ZpCIqxVOgmBHEDMyQkXo1b+hMLWxK9TNyi9eXGa0siL7nZqJ2UmgQMWZwQ8Bw=
  app: reason-one
  on:
    repo: meandmyrobot/devoffsite2018
    